version: '3.8'

services:
  perfex-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perfex-mcp-server
    restart: unless-stopped
    environment:
      # These environment variables should be set in your deployment environment
      # or via a .env file for local development
      - PERFEX_API_URL=${PERFEX_API_URL}
      - PERFEX_API_KEY=${PERFEX_API_KEY}
      - NODE_ENV=production
      - MCP_HTTP_MODE=true
      - PORT=3000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mcp-network:
    driver: bridge